# Generated by Django 5.0.1 on 2024-02-18 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_prod_id'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product'),
        ),
    ]
