# Generated by Django 5.0.1 on 2024-02-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
