# Generated by Django 5.0.1 on 2024-02-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
